# action 的名称
name: 推送 Docker 镜像
# 触发 action 的事件
on:
  push:
    # main 分支有推送时触发
    branches:
      - 'master'
    # tag 新建时触发
    tags:
      - '*'

jobs:
  push_to_registry:
    name: 推送到 Docker Hub
    # 基于指定平台构建。有 win、ubuntu、mac 可选
    # 消耗的分钟倍数：linux 1x、win 2x、mac 10x
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      # https://github.com/actions/checkout
      - name: Check out the repo
        uses: actions/checkout@v3

      # 登录到 Docker hub
      # https://github.com/docker/login-action
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # 登录用的账号密码。在项目的 Settings -> Secrets and variables -> Actions 中配置
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # 在 DockerHub 的 Account Settings -> Security -> Access Token 中配置
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 从触发此次 action 的事件中提取源数据（tag、label 什么的）
      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # 提取出来的源数据用于这个镜像
          images: mokeyjay/pixiv-daily-ranking-widget

      # 使用 buildx 作为构建器，以支持多平台构建之类的能力
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 构建并推送
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      # 更新镜像描述（即 README）
      # https://github.com/peter-evans/dockerhub-description
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mokeyjay/pixiv-daily-ranking-widget